[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

[formatter.prettier]
command = "prettier"
options = ["--check"]
includes = [
  "*.yaml",
  "*.yml",
  "*.md",
]
