cargo-features = ["per-package-target"]

[package]
name = "zynq7000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

forced-target = "armv7a-none-eabi"

[dependencies]
armv7a = { git = "https://github.com/moritz-meier/armv7a.git" }
